import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Main documentation sidebar - autogenerated from file structure
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // generate from docs folder
    },
  ],
};

export default sidebars;
